### ISSUE TITLE
Forced OS Override

### ISSUE THREAD

**Issue by drock577** [smudge202/software-inc#1]
Is the forced OS Override added to the repo? Will it be added to the OS or a new software type?

**Comment by drock577** [comment]
For the forced OS Override add : 
`<Random></Random>
<Popularity></Popularity>`
And give them really small values. That way the Simulation won't act up. Since the game is assuming 0 for both values, it cannot compute.

**Comment by smudge202** [comment]
I removed the forced OS overrides. They actually aren't the issue, because if I switch them to vital I still get issues.

My understanding is that any tags you do not specify for overrdes are inherited from the base types. I'll give it a try and let you know though.

**Comment by smudge202** [comment]
Yeh, unfortunately providing values for those fields doesn't resolve the market simulation issues.

```xml
    <Random>0</Random>
    <Popularity>0.9</Popularity>
```

![general error](http://puu.sh/mUK6O/20149672a7.png)

![stack trace](http://puu.sh/mUKb4/662fd19d9c.png)

**Comment by smudge202** [comment]
For reference, the Forced OS Override is visible in the `Operating-System.xml` diff on [this commit](https://github.com/smudge202/software-inc/commit/6b9a4482e8c8f89290b3de9edd4be36114625fef).

**Comment by smudge202** [comment]
These issues were resolved by removing company types related to remove software types. Current alpha-7-7 branch reflects this.
